name: gh-env

channels:
  - conda-forge

dependencies:
  - python=3.9.7
  - beautifulsoup4
  - ipycache
  - ipykernel
  - ipython
  - ipywidgets
  - lxml
  - myst-nb
  - myst-parser
  - nbsphinx
  - numpydoc
  - palettable
  - pandas
  - requests
  - sphinx
  - sphinx-book-theme
  - tqdm
  - pip
  - pip:
    - pygieons
    - pypistats
